Clone laxkit if not supplied or found

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -18,6 +18,9 @@ FINALPREFIX=""
 #LAXDIR="/usr/local/include/lax"
 LAXDIR="`pwd`/laxkit/lax"
 
+# in case no Laxkit found, download manually
+LAXREPO="https://github.com/Laidout/laxkit.git"
+
 
  # for some plugins:
 GEGLVERSION='gegl-0.3'
@@ -61,7 +64,7 @@ while true ; do
         echo " --prefix=/where/to/install   Default /usr/local"
         echo " --finalprefix=/really/where  Optional, final install destination, when prefix is just a"
         echo "                                temporary staging area, before actual installation."
-        echo " --laxkit=/laxkit/headers     Default in releases is ./laxkit, since the Laxkit"
+        echo " --laxkit=/laxkit/headers     Default in releases is ./laxkit/lax, since the Laxkit"
         echo "                                is currently included in release downloads"
 		echo " --version=OtherVersionNum    You may force Laidout to compile with a different"
 		echo "                                version string. This will make ~/.config/laidout/(version)"
@@ -172,6 +175,10 @@ while true ; do
         fi
 		LAXDIR="$optarg"
 		#echo laxkit $optarg; 
+		if [ ! -e $LAXDIR ] ; then
+		  echo "Missing Laxkit at $LAXDIR"
+		  exit 1
+		fi
 		shift ;;
     --language)
         if [ -z $optarg ] ; then 
@@ -209,16 +216,23 @@ fi
 
 echo "Done parsing options.";
 
-
 ##
 ## Configure Laxkit if necessary, and pass in relevant flags
 ##
+if [ ! -e $LAXDIR ] ; then
+    #clone if not found
+    git clone $LAXREPO
+	$LAXDIR = `pwd`/laxkit/lax
+fi
+
 if [ ! -e $LAXDIR/configured.h ] ; then
 	LAXTRAS=""
 	if [ $USESQLITE == "no" ] ; then LAXTRAS="$LAXTRAS --disable-sqlite"; fi
 	if [ $RELOCATABLE == "yes" ] ; then LAXTRAS="$LAXTRAS --relocatable"; fi
 	echo "Laxkit not configured, configuring with defaults...";
+	CURDIR=`pwd`
 	cd $LAXDIR/.. && ./configure
+	cd $CURDIR
 fi
 
 
@@ -313,7 +327,7 @@ fi
  ##
  ## generate src/version.h
  ## 
-echo "Generating src/version.h..."
+echo "Generating src/version.h... from `pwd`"
 
 echo " // ---- THIS FILE IS AUTOMATICALLY GENERATED -----" > src/version.h
 echo " // ----          BY ../configure             -----" >> src/version.h
